### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by Cyberpwn3** [whoozi/Cosmetic#1]
Every time I use /stealsoul, my game crashes to desktop. I don't know what are presets. I don't know what "Enable Shang Tsung" is supposed to do.

**Comment by whoozi** [comment]
I'm unable to reproduce any crash with my game with only Cosmetic enabled.

Presets are your saved appearances when you edit a character, like when you use a Fantasia or create a new character for example.

Shang Tsung is the option to enable appearance "stealing" or copying. When you do /stealsoul on another targeted player, and then enable shang tsung, you'll copy their appearance.
